allowBuilds:
  bun: true

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

onlyBuiltDependencies:
  - bun

preferWorkspacePackages: true

publicHoistPattern:
  - zod

saveWorkspaceProtocol: false
