/**
 * ═══════════════════════════════════════════════════════════
 * ⚠️  注意 / WARNING ⚠️
 * ═══════════════════════════════════════════════════════════
 *
 * 此檔案由 build:config-defaults 腳本自動生成
 * This file is auto-generated by build:config-defaults script
 *
 * 請勿手動編輯此檔案！
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * 要更新預設值，請修改 src/config/schema.ts 中的 Schema 定義
 * To update defaults, modify the Schema definition in src/config/schema.ts
 *
 * ═══════════════════════════════════════════════════════════
 */
import { IAriseConfig } from "../config/schema";

/**
 * 建立預設配置物件
 * Create default configuration object
 *
 * 此函式從 AriseConfigSchema 自動提取默認值
 * This function extracts default values from AriseConfigSchema automatically
 *
 * @returns 包含所有預設值的配置物件
 */
export function createDefaultConfig(): IAriseConfig
{
	return {
		"show_banner": true,
		"banner_every_session": false,
		"output_shaping": {
			"max_chars": 12000,
			"preserve_errors": true
		},
		"compaction": {
			"threshold_percent": 80,
			"preserve_todos": true
		},
		"background": {
			"poll_interval": 2000,
			"retry_delay_increment": 5000,
			"retry_delay_max": 60000,
			"auto_resume": {
				"enabled": false,
				"max_retries": 3,
				"retry_delay": 5000,
				"on_error": "ignore",
				"target": "background",
				"safety_prompt": "請依序檢查：\n1. 若後續任務明確可行，繼續執行\n2. 若存在潛在風險（如破壞性變更、資料遺失、安全疑慮、或將更動專案外檔案），請先停止並說明風險，請求用戶確認\n3. 若需求模糊或資訊不足，請停止並說明疑點，請求用戶澄清\n4. 若非用戶明確要求撤銷更改或刪除檔案，請先詢問用戶，獲得許可後才執行\n\n**若任務已完成，請複查並總結結果後結束**\n\nCheck in order:\n1. If the next step is clear and actionable, proceed.\n2. If potential risks exist (e.g., destructive changes, data loss, security concerns, or modifying files outside the project), stop, explain the risks, and request confirmation.\n3. If requirements are ambiguous or information is insufficient, stop, state the uncertainty, and request clarification.\n4. Unless the user explicitly requests to revert changes or delete files, always ask for permission first and only proceed after obtaining user consent.\n\n**If the task is complete, review and summarize the results, then end.**"
			}
		},
		"debug": {
			"enabled": false,
			"level": "warn"
		}
	} as any;
}
