/**
 * ═══════════════════════════════════════════════════════════
 * ⚠️  注意 / WARNING ⚠️
 * ═══════════════════════════════════════════════════════════
 *
 * 此檔案由 build:config-defaults 腳本自動生成
 * This file is auto-generated by build:config-defaults script
 *
 * 請勿手動編輯此檔案！
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * 要更新預設值，請修改 src/config/schema.ts 中的 Schema 定義
 * To update defaults, modify the Schema definition in src/config/schema.ts
 *
 * ═══════════════════════════════════════════════════════════
 */
import { IAriseConfig } from "../config/schema";

/**
 * 建立預設配置物件
 * Create default configuration object
 *
 * 此函式從 AriseConfigSchema 自動提取默認值
 * This function extracts default values from AriseConfigSchema automatically
 *
 * @returns 包含所有預設值的配置物件
 */
export function createDefaultConfig(): IAriseConfig
{
	return {
		"show_banner": true,
		"banner_every_session": false,
		"output_shaping": {
			"max_chars": 12000,
			"preserve_errors": true
		},
		"compaction": {
			"threshold_percent": 80,
			"preserve_todos": true
		},
		"background": {
			"poll_interval": 2000,
			"retry_delay_increment": 5000,
			"retry_delay_max": 60000,
			"auto_resume": {
				"enabled": false,
				"max_retries": 3,
				"retry_delay": 5000,
				"on_error": "ignore",
				"target": "background"
			}
		},
		"debug": {
			"enabled": false,
			"level": "warn"
		}
	} as any;
}
