/**
 * ═══════════════════════════════════════════════════════════
 * ⚠️  注意 / WARNING ⚠️
 * ═══════════════════════════════════════════════════════════
 *
 * 此檔案由 build:version 腳本自動生成
 * This file is auto-generated by build:version script
 *
 * 請勿手動編輯此檔案！
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * 要更新版本號，請修改 package.json 中的 version 欄位
 * To update the version, modify the version field in package.json
 *
 * ═══════════════════════════════════════════════════════════
 */

/**
 * 插件版本號
 * Plugin version
 *
 * @type {string}
 */
export const PLUGIN_VERSION = "0.1.13" as const;

/**
 * 插件版本號字串（含 v 前綴）
 * Plugin version string (with v prefix)
 *
 * @type {string}
 */
export const PLUGIN_VERSION_STRING = "v0.1.13" as const;

/**
 * 插件首頁
 * Plugin homepage
 *
 * @type {string}
 */
export const PLUGIN_VERSION_HOMEPAGE = "https://github.com/bluelovers/opencode-arise#readme" as const;
