/**
 * 版本號生成腳本
 * Version generation script
 *
 * 在構建前將當前版本號寫入 src/types/version.ts
 * Write current version to src/types/version.ts before build
 *
 * 運行方式 / Usage:
 *   bun test/scripts/generate-version.ts
 *   tsx test/scripts/generate-version.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readJSONSync } from "fs-extra";
import { dirname, join } from "upath2";
import { fileURLToPath } from "node:url";

// 引入專案根路徑
// Import project root path
import { __ROOT } from "../../__root";

// 使用 __ROOT 定義路徑
// Use __ROOT for paths
const packageJsonPath = join(__ROOT, "package.json");
const versionFilePath = join(__ROOT, "src", "types", "version.ts");

/**
 * 讀取 package.json 中的版本號
 * Read version from package.json
 */
const packageJson = readJSONSync(packageJsonPath);
const version = packageJson.version;

/**
 * 生成 version.ts 內容
 * Generate version.ts content
 */
function generateVersionFile()
{
  return `/**
 * ═══════════════════════════════════════════════════════════
 * ⚠️  注意 / WARNING ⚠️
 * ═══════════════════════════════════════════════════════════
 *
 * 此檔案由 build:version 腳本自動生成
 * This file is auto-generated by build:version script
 *
 * 請勿手動編輯此檔案！
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * 要更新版本號，請修改 package.json 中的 version 欄位
 * To update the version, modify the version field in package.json
 *
 * ═══════════════════════════════════════════════════════════
 */

/**
 * 插件版本號
 * Plugin version
 *
 * @type {string}
 */
export const PLUGIN_VERSION = "${version}" as const;

/**
 * 插件版本號字串（含 v 前綴）
 * Plugin version string (with v prefix)
 *
 * @type {string}
 */
export const PLUGIN_VERSION_STRING = "v${version}" as const;

/**
 * 插件首頁
 * Plugin homepage
 *
 * @type {string}
 */
export const PLUGIN_VERSION_HOMEPAGE = "${packageJson.homepage}" as const;
`;
}

// 主邏輯
const versionFileContent = generateVersionFile();

// 寫入檔案
writeFileSync(versionFilePath, versionFileContent, "utf-8");

console.log(`✅ Version generated: ${version}`);
console.log(`   Output: ${versionFilePath}`);
