/**
 * 預設配置生成腳本
 * Default config generation script
 *
 * 在構建前從 AriseConfigSchema 提取默認值並寫入 src/types/config-defaults.ts
 * Extract default values from AriseConfigSchema and write to src/types/config-defaults.ts before build
 *
 * 運行方式 / Usage:
 *   bun test/scripts/generate-config-defaults.ts
 *   tsx test/scripts/generate-config-defaults.ts
 *
 * ⚠️ 重要說明 / Important Notes:
 * - 此腳本使用 extractDefaultsFromJSONSchema 自動從 Zod Schema 提取預設值
 * - 新增 schema 欄位時，請確保欄位有適當的預設值（.default() 或 .optional()）
 * - 預設值會自動出現在產生的 createDefaultConfig() 函式中
 * - 驗證函式 validateDefaults() 需要同步更新，以驗證新增的欄位
 *
 * - extractDefaultsFromJSONSchema automatically extracts default values from Zod Schema
 * - When adding schema fields, ensure fields have appropriate defaults (.default() or .optional())
 * - Default values will automatically appear in the generated createDefaultConfig() function
 * - Validation function validateDefaults() needs to be updated to validate new fields
 */

// @ts-ignore
import { writeFileSync } from "fs-extra";
// @ts-ignore
import { join } from "path";
import { describe, expect, it } from "bun:test";

// 引入專案根路徑
// Import project root path
import { __ROOT } from "../../__root";

// 引入 Zod Schema 和提取函式
// Import Zod Schema and extraction function
import { AriseConfigSchema, IAriseConfig } from "../../src/config/schema";
import { extractDefaultsFromJSONSchema } from "../../src/utils/type/zod-defaults";

// 使用 __ROOT 定義路徑
// Use __ROOT for paths
const configDefaultsFilePath = join(__ROOT, "src", "types", "config-defaults.ts");

/**
 * 驗證所有在 createDefaultConfig() 中實際存在的預設值
 * Validate all default values that actually exist in createDefaultConfig()
 *
 * 驗證每個欄位：
 * - 數字欄位必須 > 0
 * - 布林欄位必須是布林值
 * - 字串欄位必須是字串
 *
 * @param defaults - 要驗證的預設配置物件
 * @throws 如果驗證失敗則拋出錯誤
 */
function validateDefaults(defaults: IAriseConfig): void
{
	// 驗證 show_banner（布林）
	expect(defaults.show_banner).toBeBoolean();

	// 驗證 banner_every_session（布林）
	expect(defaults.banner_every_session).toBeBoolean();

	// 驗證 output_shaping
	expect(defaults.output_shaping!.max_chars).toBeGreaterThan(0);
	expect(defaults.output_shaping!.preserve_errors).toBeBoolean();

	// 驗證 compaction
	expect(defaults.compaction!.threshold_percent).toBeGreaterThan(0);
	expect(defaults.compaction!.preserve_todos).toBeBoolean();

	// 驗證 background
	expect(defaults.background!.poll_interval).toBeGreaterThan(0);
	expect(defaults.background!.retry_delay_increment).toBeGreaterThan(0);
	expect(defaults.background!.retry_delay_max).toBeGreaterThan(0);

	// 驗證 background.auto_resume
	expect(defaults.background!.auto_resume!.enabled).toBeBoolean();
	expect(defaults.background!.auto_resume!.max_retries).toBeGreaterThan(0);
	expect(defaults.background!.auto_resume!.retry_delay).toBeGreaterThan(0);
	expect(defaults.background!.auto_resume!.on_error).toBeString();
	expect(defaults.background!.auto_resume!.target).toBeString();

	// 驗證 debug
	expect(defaults.debug!.enabled).toBeBoolean();
	expect(defaults.debug!.level).toBeString();
}

/**
 * 生成 config-defaults.ts 內容
 * Generate config-defaults.ts content
 */
function generateConfigDefaultsFile(): string
{
	// 從 Schema 提取默認值
	// Extract defaults from Schema
	const defaults = extractDefaultsFromJSONSchema(AriseConfigSchema);

	// 驗證預設值存在且數字 > 0
	// Validate defaults exist and numbers > 0
	validateDefaults(defaults);

	// 轉換為 JSON 格式
	// Convert to JSON format
	const defaultsCode = JSON.stringify(defaults, null, '\t')
		.split('\n')
		.map((line, index) => (index === 0 ? line : '\t' + line))
		.join('\n');

	return `/**
 * ═══════════════════════════════════════════════════════════
 * ⚠️  注意 / WARNING ⚠️
 * ═══════════════════════════════════════════════════════════
 *
 * 此檔案由 build:config-defaults 腳本自動生成
 * This file is auto-generated by build:config-defaults script
 *
 * 請勿手動編輯此檔案！
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * 要更新預設值，請修改 src/config/schema.ts 中的 Schema 定義
 * To update defaults, modify the Schema definition in src/config/schema.ts
 *
 * ═══════════════════════════════════════════════════════════
 */
import { IAriseConfig } from "../config/schema";

/**
 * 建立預設配置物件
 * Create default configuration object
 *
 * 此函式從 AriseConfigSchema 自動提取默認值
 * This function extracts default values from AriseConfigSchema automatically
 *
 * @returns 包含所有預設值的配置物件
 */
export function createDefaultConfig(): IAriseConfig
{
	return ${defaultsCode} as any;
}
`;
}

// 主邏輯
const configDefaultsFileContent = generateConfigDefaultsFile();

// 寫入檔案
writeFileSync(configDefaultsFilePath, configDefaultsFileContent, "utf-8");

console.log("✅ Config defaults generated successfully!");
console.log(`   Output: ${configDefaultsFilePath}`);
